<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $stateDetails = [['US','AK','Alaska','PACIFIC'],
        ['US','AL','Alabama','CENTRAL'],
        ['US','AR','Arkansas','CENTRAL'],
        ['US','AS','American Samoa','UNKNOWN'],
        ['US','AZ','Arizona','MOUNTAIN'],
        ['US','CA','California','PACIFIC'],
        ['US','CO','Colorado','MOUNTAIN'],
        ['US','CT','Connecticut','EASTERN'],
        ['US','DC','D.C.','EASTERN'],
        ['US','DE','Delaware','EASTERN'],
        ['US','FL','Florida','EASTERN'],
        ['US','FM','Micronesia','UNKNOWN'],
        ['US','GA','Georgia','EASTERN'],
        ['US','GU','Guam','UNKNOWN'],
        ['US','HI','Hawaii','PACIFIC'],
        ['US','IA','Iowa','CENTRAL'],
        ['US','ID','Idaho','MOUNTAIN'],
        ['US','IL','Illinois','CENTRAL'],
        ['US','IN','Indiana','EASTERN'],
        ['US','KS','Kansas','CENTRAL'],
        ['US','KY','Kentucky','CENTRAL'],
        ['US','LA','Louisiana','CENTRAL'],
        ['US','MA','Massachusetts','EASTERN'],
        ['US','MD','Maryland','EASTERN'],
        ['US','ME','Maine','EASTERN'],
        ['US','MH','Marshall Islands','UNKNOWN'],
        ['US','MI','Michigan','EASTERN'],
        ['US','MN','Minnesota','CENTRAL'],
        ['US','MO','Missouri','CENTRAL'],
        ['US','MP','Marianas','UNKNOWN'],
        ['US','MS','Mississippi','CENTRAL'],
        ['US','MT','Montana','MOUNTAIN'],
        ['US','NC','North Carolina','EASTERN'],
        ['US','ND','North Dakota','CENTRAL'],
        ['US','NE','Nebraska','CENTRAL'],
        ['US','NH','New Hampshire','EASTERN'],
        ['US','NJ','New Jersey','EASTERN'],
        ['US','NM','New Mexico','MOUNTAIN'],
        ['US','NV','Nevada','PACIFIC'],
        ['US','NY','New York','EASTERN'],
        ['US','OH','Ohio','EASTERN'],
        ['US','OK','Oklahoma','CENTRAL'],
        ['US','OR','Oregon','PACIFIC'],
        ['US','PA','Pennsylvania','EASTERN'],
        ['US','PR','Puerto Rico','UNKNOWN'],
        ['US','PW','Palau','UNKNOWN'],
        ['US','RI','Rhode Island','EASTERN'],
        ['US','SC','South Carolina','EASTERN'],
        ['US','SD','South Dakota','CENTRAL'],
        ['US','TN','Tennessee','UNKNOWN'],
        ['US','TX','Texas','CENTRAL'],
        ['US','UT','Utah','MOUNTAIN'],
        ['US','VA','Virginia','UNKNOWN'],
        ['US','VI','Virgin Islands','UNKNOWN'],
        ['US','VT','Vermont','EASTERN'],
        ['US','WA','Washington','PACIFIC'],
        ['US','WI','Wisconsin','CENTRAL'],
        ['US','WV','West Virginia','UNKNOWN'],
        ['US','WY','Wyoming','MOUNTAIN'],
        ['US','AA','Military Americas','UNKNOWN'],
        ['US','AE','Military Europe/ME/Canada','UNKNOWN'],
        ['US','AP','Military Pacific','UNKNOWN'],
        ['CA','AB','Alberta','UNKNOWN'],
        ['CA','MB','Manitoba','UNKNOWN'],
        ['CA','AB','Alberta','UNKNOWN'],
        ['CA','BC','British Columbia','UNKNOWN'],
        ['CA','MB','Manitoba','UNKNOWN'],
        ['CA','NB','New Brunswick','UNKNOWN'],
        ['CA','NL','Newfoundland and Labrador','UNKNOWN'],
        ['CA','NS','Nova Scotia','UNKNOWN'],
        ['CA','NT','Northwest Territories','UNKNOWN'],
        ['CA','NU','Nunavut','UNKNOWN'],
        ['CA','ON','Ontario','UNKNOWN'],
        ['CA','PE','Prince Edward Island','UNKNOWN'],
        ['CA','QC','Quebec','UNKNOWN'],
        ['CA','SK','Saskatchewan','UNKNOWN'],
        ['CA','YT','Yukon Territory','UNKNOWN'],
        ['AU','AAT','Australian Antarctic Territory','UNKNOWN'],
        ['AU','ACT','Australian Capital Territory','UNKNOWN'],
        ['AU','NT','Northern Territory','UNKNOWN'],
        ['AU','NSW','New South Wales','UNKNOWN'],
        ['AU','QLD','Queensland','UNKNOWN'],
        ['AU','SA','South Australia','UNKNOWN'],
        ['AU','TAS','Tasmania','UNKNOWN'],
        ['AU','VIC','Victoria','UNKNOWN'],
        ['AU','WA','Western Australia','PACIFIC'],
        ['BR','AC','Acre','UNKNOWN'],
        ['BR','AL','Alagoas','CENTRAL'],
        ['BR','AM','Amazonas','UNKNOWN'],
        ['BR','AP','Amapa','UNKNOWN'],
        ['BR','BA','Baia','UNKNOWN'],
        ['BR','CE','Ceara','UNKNOWN'],
        ['BR','DF','Distrito Federal','UNKNOWN'],
        ['BR','ES','Espirito Santo','UNKNOWN'],
        ['BR','FN','Fernando de Noronha','UNKNOWN'],
        ['BR','GO','Goias','UNKNOWN'],
        ['BR','MA','Maranhao','EASTERN'],
        ['BR','MG','Minas Gerais','UNKNOWN'],
        ['BR','MS','Mato Grosso do Sul','CENTRAL'],
        ['BR','MT','Mato Grosso','MOUNTAIN'],
        ['BR','PA','Para','EASTERN'],
        ['BR','PB','Paraiba','UNKNOWN'],
        ['BR','PE','Pernambuco','UNKNOWN'],
        ['BR','PI','Piaui','UNKNOWN'],
        ['BR','PR','Parana','UNKNOWN'],
        ['BR','RJ','Rio de Janeiro','UNKNOWN'],
        ['BR','RN','Rio Grande do Norte','UNKNOWN'],
        ['BR','RO','Rondonia','UNKNOWN'],
        ['BR','RR','Roraima','UNKNOWN'],
        ['BR','RS','Rio Grande do Sul','UNKNOWN'],
        ['BR','SC','Santa Catarina','EASTERN'],
        ['BR','SE','Sergipe','UNKNOWN'],
        ['BR','SP','Sao Paulo','UNKNOWN'],
        ['BR','TO','Tocatins','UNKNOWN'],
        ['NL','DR','Drente','UNKNOWN'],
        ['NL','FL','Flevoland','EASTERN'],
        ['NL','FR','Friesland','UNKNOWN'],
        ['NL','GL','Gelderland','UNKNOWN'],
        ['NL','GR','Groningen','UNKNOWN'],
        ['NL','LB','Limburg','UNKNOWN'],
        ['NL','NB','Noord Brabant','UNKNOWN'],
        ['NL','NH','Noord Holland','EASTERN'],
        ['NL','OV','Overijssel','UNKNOWN'],
        ['NL','UT','Utrecht','MOUNTAIN'],
        ['NL','ZH','Zuid Holland','UNKNOWN'],
        ['NL','ZL','Zeeland','UNKNOWN'],
        ['UK','AVON','Avon','UNKNOWN'],
        ['UK','BEDS','Bedfordshire','UNKNOWN'],
        ['UK','BERKS','Berkshire','UNKNOWN'],
        ['UK','BUCKS','Buckinghamshire','UNKNOWN'],
        ['UK','CAMBS','Cambridgeshire','UNKNOWN'],
        ['UK','CHESH','Cheshire','UNKNOWN'],
        ['UK','CLEVE','Cleveland','UNKNOWN'],
        ['UK','CORN','Cornwall','UNKNOWN'],
        ['UK','CUMB','Cumbria','UNKNOWN'],
        ['UK','DERBY','Derbyshire','UNKNOWN'],
        ['UK','DEVON','Devon','UNKNOWN'],
        ['UK','DORSET','Dorset','UNKNOWN'],
        ['UK','DURHAM','Durham','UNKNOWN'],
        ['UK','ESSEX','Essex','UNKNOWN'],
        ['UK','GLOUS','Gloucestershire','UNKNOWN'],
        ['UK','GLONDON','Greater London','UNKNOWN'],
        ['UK','GMANCH','Greater Manchester','UNKNOWN'],
        ['UK','HANTS','Hampshire','UNKNOWN'],
        ['UK','HERWOR','Hereford & Worcestershire','UNKNOWN'],
        ['UK','HERTS','Hertfordshire','UNKNOWN'],
        ['UK','HUMBER','Humberside','UNKNOWN'],
        ['UK','IOM','Isle of Man','UNKNOWN'],
        ['UK','IOW','Isle of Wight','UNKNOWN'],
        ['UK','KENT','Kent','UNKNOWN'],
        ['UK','LANCS','Lancashire','UNKNOWN'],
        ['UK','LEICS','Leicestershire','UNKNOWN'],
        ['UK','LINCS','Lincolnshire','UNKNOWN'],
        ['UK','MERSEY','Merseyside','UNKNOWN'],
        ['UK','NORF','Norfolk','UNKNOWN'],
        ['UK','NHANTS','Northamptonshire','UNKNOWN'],
        ['UK','NTHUMB','Northumberland','UNKNOWN'],
        ['UK','NOTTS','Nottinghamshire','UNKNOWN'],
        ['UK','OXON','Oxfordshire','UNKNOWN'],
        ['UK','SHROPS','Shropshire','UNKNOWN'],
        ['UK','SOM','Somerset','UNKNOWN'],
        ['UK','STAFFS','Staffordshire','UNKNOWN'],
        ['UK','SUFF','Suffolk','UNKNOWN'],
        ['UK','SURREY','Surrey','UNKNOWN'],
        ['UK','SUSS','Sussex','UNKNOWN'],
        ['UK','WARKS','Warwickshire','UNKNOWN'],
        ['UK','WMID','West Midlands','UNKNOWN'],
        ['UK','WILTS','Wiltshire','UNKNOWN'],
        ['UK','YORK','Yorkshire','UNKNOWN'],
        ['EI','CO ANTRIM','County Antrim','UNKNOWN'],
        ['EI','CO ARMAGH','County Armagh','UNKNOWN'],
        ['EI','CO DOWN','County Down','UNKNOWN'],
        ['EI','CO FERMANAGH','County Fermanagh','UNKNOWN'],
        ['EI','CO DERRY','County Londonderry','UNKNOWN'],
        ['EI','CO TYRONE','County Tyrone','UNKNOWN'],
        ['EI','CO CAVAN','County Cavan','UNKNOWN'],
        ['EI','CO DONEGAL','County Donegal','UNKNOWN'],
        ['EI','CO MONAGHAN','County Monaghan','UNKNOWN'],
        ['EI','CO DUBLIN','County Dublin','UNKNOWN'],
        ['EI','CO CARLOW','County Carlow','UNKNOWN'],
        ['EI','CO KILDARE','County Kildare','UNKNOWN'],
        ['EI','CO KILKENNY','County Kilkenny','UNKNOWN'],
        ['EI','CO LAOIS','County Laois','UNKNOWN'],
        ['EI','CO LONGFORD','County Longford','UNKNOWN'],
        ['EI','CO LOUTH','County Louth','UNKNOWN'],
        ['EI','CO MEATH','County Meath','UNKNOWN'],
        ['EI','CO OFFALY','County Offaly','UNKNOWN'],
        ['EI','CO WESTMEATH','County Westmeath','UNKNOWN'],
        ['EI','CO WEXFORD','County Wexford','UNKNOWN'],
        ['EI','CO WICKLOW','County Wicklow','UNKNOWN'],
        ['EI','CO GALWAY','County Galway','UNKNOWN'],
        ['EI','CO MAYO','County Mayo','UNKNOWN'],
        ['EI','CO LEITRIM','County Leitrim','UNKNOWN'],
        ['EI','CO ROSCOMMON','County Roscommon','UNKNOWN'],
        ['EI','CO SLIGO','County Sligo','UNKNOWN'],
        ['EI','CO CLARE','County Clare','UNKNOWN'],
        ['EI','CO CORK','County Cork','UNKNOWN'],
        ['EI','CO KERRY','County Kerry','UNKNOWN'],
        ['EI','CO LIMERICK','County Limerick','UNKNOWN'],
        ['EI','CO TIPPERARY','County Tipperary','UNKNOWN'],
        ['EI','CO WATERFORD','County Waterford','UNKNOWN']];

        \App\Models\State::whereNotNull('country')->delete();
        foreach($stateDetails as $stateDetail){
            $state = \App\Models\State::Create(
                [
                    'state' => $stateDetail[1] ?? '',
                    'name' => $stateDetail[2] ?? '',
                    'country' => $stateDetail[0] ?? '',
                    'timezone' => $stateDetail[3] ?? ''
                ]
            );
        }
    }
}
